
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file:
    name: D:\BlogSite_Backend\logstash\logstash.log

springdoc:
  packagesToScan: com.blogsite
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: pass@word1
  jpa: 
    hibernate: 
      ddl-auto: update
server:
  port: 8081